name: form
description: Easy form validation and state management
version: 0.0.2
homepage: https://github.com/EdsonOnildoJR/form

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^2.0.0+1
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
